### ISSUE TITLE
Question about calculating eigenvectors

### ISSUE THREAD

**Issue by leshanshui-yang** [shenyangHuang/SCPD#1]
Hello,

I am a PhD student closely following your recent research on anomaly detection with DOS. Thank you for sharing the code and the presentation at TGL-TG !
I noticed that in the video and the Def. 2 of the Arxiv version article, you mention the computation of the eigenvectors, I would like to ask how can I get the q or the eigenvectors in the code, what are the variables corresponding to them ?
Thank you in advance.

Leshanshui

**Comment by shenyangHuang** [comment]
Hi Leshanshui,

Thanks for your interest in our work and sorry for just seeing the issue. Feel free to reach out to me by email as well in the future. 
Yes, the eigenvectors can be approximated too however it requires using the MATLAB code under `SCPD/subroutines/ADOS`. Because the interaction with eigenvectors are approximated with the GQL approximation method which was only implemented in MATLAB so far. Hope it answers your question. 

Best,
Andy

**Comment by leshanshui-yang** [comment]
Hi Andy,

Thanks for your reply, it answered my question clearly.

Best,
Leshanshui

**Comment by shenyangHuang** [comment]
Thanks again for pointing this out. I will close this issue now
